<?php
/**
 * tools/csv_to_php.php
 *
 * OPTIONAL performance tool — only needed if your site has thousands of URLs
 * and you want to avoid parsing the CSV on every single request.
 *
 * For 150–200 URLs (your current size), index.php reads the CSV directly
 * and is fast enough. You do NOT need to run this script right now.
 *
 * IF YOU EVER NEED IT:
 *   Run from the command line inside the go2trek-redirects/ folder:
 *     php tools/csv_to_php.php
 *
 *   This generates a redirects.php file containing a pre-built PHP array.
 *   Then uncomment the require_once line in index.php to use it.
 *
 * WHEN TO USE:
 *   - 1000+ URLs in redirect_map.csv
 *   - Hosting provider complains about CPU usage
 *   - You want to squeeze out every millisecond of performance
 */

$csv_path = __DIR__ . '/../redirects_map.csv';
$out_path = __DIR__ . '/../redirects.php';

if (!file_exists($csv_path)) {
    die("ERROR: redirect_map.csv not found at: $csv_path\n");
}

$map = [];
$handle = fopen($csv_path, 'r');
$is_first_row = true;
$count = 0;

while (($row = fgetcsv($handle)) !== false) {
    if ($is_first_row) { $is_first_row = false; continue; }
    if (count($row) < 2) continue;

    $old = trim($row[0]);
    $new = trim($row[1]);
    if ($old === '' || $new === '') continue;

    $key = rtrim(strtolower(rawurldecode($old)), '/');
    if ($key === '') $key = '/';

    $map[$key] = $new;
    $count++;
}
fclose($handle);

// Write PHP array file
$output = "<?php\n";
$output .= "// Auto-generated by tools/csv_to_php.php — do not edit manually.\n";
$output .= "// Re-run this script after updating redirect_map.csv.\n";
$output .= "// Generated: " . date('Y-m-d H:i:s') . " | Entries: $count\n";
$output .= "return [\n";

foreach ($map as $old => $new) {
    $output .= '    ' . var_export($old, true) . ' => ' . var_export($new, true) . ",\n";
}

$output .= "];\n";

file_put_contents($out_path, $output);
echo "Done. $count redirects written to redirects.php\n";
